### ISSUE TITLE
citation source needed 

### ISSUE THREAD

**Issue by epogrebnyak** [JasonShin/fp-core.rs#60]
Why not mention you are drawing the [contents of the jargon](https://github.com/JasonShin/fp-core.rs#functional-programming-jargon-in-rust) from https://github.com/hemanth/functional-programming-jargon? This some else's writing and should be credited.

**Comment by JasonShin** [comment]
@epogrebnyak hey, we already have a link to `Rust World` pointing to this project on hemanth/functional-programming-jargon project, check out on their README page

**Comment by hemanth** [comment]
The main project is under MIT lisence, so it would good to adhere to it? Maybe a link back to the main repo would be a good thing to do.

**Comment by JasonShin** [comment]
@hemanth Ok sure, we agree ;) BTW thanks for your initial work! We've turned it into a usable Rust library based on your idea!

**Comment by JasonShin** [comment]
Citation to the original project is now included in https://github.com/JasonShin/fp-core.rs/pull/61 !
